### PR TITLE
Initial PR for path_finding

### PR DESCRIPTION
**Pull request by Matnay**
This PR introduces the following changes:

1. Major refactoring to streamline data and workflow
2. Addition of EfficientDet and EfficientDet-Lite models for landmark detection with the option of acceleration with the Coral Edge TPU on a Raspberry Pi
3. Addition of Jupyter Notebooks to easily replicate model training and deployment with Google Colab
4. Added cone_mapper package and convenience scripts for installation

### CODE REVIEW

**Review by 2ahunter — APPROVED** [review]
Approved, thanks Pranay.

**Comment by caiespin** [comment]
Approved :) Thank you, Pranay!

**Review by caiespin — COMMENTED** [review]
Approved :) Thank you, Pranay!

**Review by caiespin — COMMENTED** [review]
Approved :) Thank you, Pranay!

**Pull request merged**
